name: Python Master Workflow
on:
  push:
    branches:
      - 'master'
jobs:
  codecov:
    name: test
    runs-on: ubuntu-18.04
    
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: 3.8
      - name: Generate coverage report
        run: |
          pwd
          ls
          python3 setup.py test
          python3 -m unittest tests/*py
